# Generated by Django 3.1.6 on 2021-02-17 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('MVZ_Department', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='МВЗ отдела')),
                ('name_Departmnet', models.CharField(max_length=40, verbose_name='Название отдела')),
            ],
        ),
        migrations.CreateModel(
            name='Sotrudnik',
            fields=[
                ('tabel_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Табельный номер')),
                ('name_sotridnik', models.CharField(max_length=40, verbose_name='ФИО')),
            ],
        ),
        migrations.CreateModel(
            name='Type_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_status', models.CharField(max_length=20, verbose_name='Тип статуса')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse_device',
            fields=[
                ('id_Device_on_Table', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер устройства в ситсеме')),
                ('type_device', models.CharField(max_length=40, verbose_name='Тип устройства')),
                ('number_PC_ID', models.CharField(max_length=40, verbose_name='Имя устройства')),
                ('serial_number_device', models.CharField(max_length=50, verbose_name='Серийный номер')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('date_postavki', models.DateTimeField(auto_now_add=True, verbose_name='Дата поставки')),
                ('MVZ_Device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.department', verbose_name='МВЗ')),
                ('status_devices', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.type_status', verbose_name='ID статус')),
            ],
        ),
        migrations.CreateModel(
            name='Repair_device',
            fields=[
                ('id_Repair', models.AutoField(primary_key=True, serialize=False, verbose_name='Запись в таблице Ремонт')),
                ('number_repair', models.IntegerField(verbose_name='Номер ремонта')),
                ('firm_repair', models.CharField(max_length=40, verbose_name='Ремонтная контора')),
                ('cost_repair', models.IntegerField(default=1000, verbose_name='Стоимость ремонта')),
                ('date_v_remont', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки в ремонт')),
                ('date_iz_remonta', models.DateTimeField(auto_now_add=True, verbose_name='Дата приемки из ремонта')),
                ('number_PC_ID_repair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.warehouse_device', verbose_name='Имя устройства на ремонт')),
                ('status_repair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.type_status', verbose_name='ID статус')),
            ],
        ),
    ]
