# Generated by Django 3.1.6 on 2021-02-18 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0002_repair_device_primechanie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair_device',
            name='number_PC_ID_repair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='invent.warehouse_device', verbose_name='Имя устройства на ремонт'),
        ),
        migrations.AlterField(
            model_name='repair_device',
            name='status_repair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='invent.type_status', verbose_name='ID статус'),
        ),
    ]
