# Generated by Django 3.1.6 on 2021-02-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0003_auto_20210218_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair_device',
            name='date_iz_remonta',
            field=models.DateTimeField(verbose_name='Дата приемки из ремонта'),
        ),
        migrations.RemoveField(
            model_name='repair_device',
            name='number_PC_ID_repair',
        ),
        migrations.AddField(
            model_name='repair_device',
            name='number_PC_ID_repair',
            field=models.ManyToManyField(blank=True, related_name='Repair_device', to='invent.Warehouse_device', verbose_name='Имя устройства на ремонт'),
        ),
        migrations.AlterField(
            model_name='repair_device',
            name='status_repair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.type_status', verbose_name='ID статус'),
        ),
    ]
