# Generated by Django 3.1.6 on 2021-02-18 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0004_auto_20210218_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse_device',
            name='primechanie',
            field=models.CharField(default=1, max_length=300, verbose_name='Примечание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repair_device',
            name='date_iz_remonta',
            field=models.DateTimeField(blank=True, verbose_name='Дата приемки из ремонта'),
        ),
        migrations.AlterField(
            model_name='repair_device',
            name='date_v_remont',
            field=models.DateTimeField(verbose_name='Дата отправки в ремонт'),
        ),
        migrations.RemoveField(
            model_name='repair_device',
            name='number_PC_ID_repair',
        ),
        migrations.AddField(
            model_name='repair_device',
            name='number_PC_ID_repair',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invent.warehouse_device', verbose_name='Имя устройства на ремонт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehouse_device',
            name='date_postavki',
            field=models.DateTimeField(verbose_name='Дата поставки'),
        ),
    ]
