# Generated by Django 3.1.6 on 2021-02-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0005_auto_20210218_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse_device',
            name='slug_devices',
            field=models.SlugField(default=1, max_length=200, verbose_name='Ссылка URL'),
            preserve_default=False,
        ),
    ]
