# Generated by Django 3.1.6 on 2021-02-19 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0006_warehouse_device_slug_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair_device',
            name='id_Device_on_repair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.warehouse_device', verbose_name='Имя устройства СВЯЗЬ'),
        ),
        migrations.AlterField(
            model_name='repair_device',
            name='number_PC_ID_repair',
            field=models.CharField(max_length=40, verbose_name='Имя устройства на ремонт для ПОИСКА'),
        ),
    ]
