# Generated by Django 3.1.6 on 2021-03-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0007_auto_20210219_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse_device',
            name='date_postavki',
            field=models.DateTimeField(blank=True, verbose_name='Дата поставки'),
        ),
    ]
