# Generated by Django 3.1.6 on 2021-03-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0009_auto_20210320_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair_device',
            name='date_iz_remonta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата приемки из ремонта'),
        ),
        migrations.AlterField(
            model_name='repair_device',
            name='date_v_remont',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки в ремонт'),
        ),
    ]
