# Generated by Django 3.1.6 on 2021-05-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0010_auto_20210321_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repair_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_status_repair', models.CharField(max_length=20, verbose_name='Статус ремонта')),
            ],
        ),
        migrations.AlterField(
            model_name='repair_device',
            name='firm_repair',
            field=models.CharField(max_length=40, verbose_name='Фирма'),
        ),
        migrations.AlterField(
            model_name='repair_device',
            name='id_Repair',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Номер ремонта'),
        ),
        migrations.AlterField(
            model_name='repair_device',
            name='number_PC_ID_repair',
            field=models.CharField(max_length=40, verbose_name='Имя устройства на ремонт'),
        ),
        migrations.AlterField(
            model_name='repair_device',
            name='number_repair',
            field=models.IntegerField(verbose_name='Номер АКТА'),
        ),
    ]
