# Generated by Django 3.1.6 on 2021-05-12 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0011_auto_20210512_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair_device',
            name='status_repair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.repair_status', verbose_name='ID статус'),
        ),
    ]
