# Generated by Django 3.1.6 on 2021-05-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0012_auto_20210512_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse_device',
            name='who_change',
            field=models.CharField(default=1, max_length=40, verbose_name='Кто изменил'),
            preserve_default=False,
        ),
    ]
